version: '3.4'

services:
  bloghub:
    image: bloghub
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 8000:8000
    command: gunicorn --bind 0.0.0.0:8000 backend.bloghub.bloghub.wsgi:application
