# Generated by Django 5.1.7 on 2025-04-10 08:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_like'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='repost_from',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reposts', to='blog.post', verbose_name='Репост от'),
        ),
    ]
